package com.ironlog.shared.store

import com.ironlog.shared.backup.BackupExercise

/** Initial catalog mirrors Android; imported IDs always remain authoritative. */
object DefaultExerciseCatalog {
    fun exercises(): List<BackupExercise> = listOf(
        exercise(1, "Bankdrücken (Langhantel)", "BRUST", "TRIZEPS,SCHULTERN", "LANGHANTEL"),
        exercise(2, "Bankdrücken (Kurzhantel)", "BRUST", "TRIZEPS,SCHULTERN", "KURZHANTEL"),
        exercise(3, "Schrägbankdrücken (Langhantel)", "BRUST", "TRIZEPS,SCHULTERN", "LANGHANTEL"),
        exercise(4, "Schrägbankdrücken (Kurzhantel)", "BRUST", "TRIZEPS,SCHULTERN", "KURZHANTEL"),
        exercise(5, "Negativbankdrücken (Langhantel)", "BRUST", "TRIZEPS", "LANGHANTEL"),
        exercise(6, "Fliegende (Kurzhantel)", "BRUST", "", "KURZHANTEL"),
        exercise(7, "Cable Fly", "BRUST", "", "KABEL"),
        exercise(8, "Cable Fly obere Brust", "BRUST", "SCHULTERN", "KABEL"),
        exercise(9, "Butterfly Maschine", "BRUST", "", "MASCHINE"),
        exercise(10, "Brustpresse (Maschine)", "BRUST", "TRIZEPS,SCHULTERN", "MASCHINE"),
        exercise(11, "Liegestütze", "BRUST", "TRIZEPS,SCHULTERN,CORE", "EIGENGEWICHT"),
        exercise(12, "Dips (Brust)", "BRUST", "TRIZEPS,SCHULTERN", "EIGENGEWICHT"),
        exercise(13, "Langhantelrudern", "RUECKEN", "BIZEPS", "LANGHANTEL"),
        exercise(14, "Kurzhantelrudern", "RUECKEN", "BIZEPS", "KURZHANTEL"),
        exercise(15, "Klimmzug", "RUECKEN", "BIZEPS", "EIGENGEWICHT"),
        exercise(16, "Klimmzug (Untergriff)", "RUECKEN", "BIZEPS", "EIGENGEWICHT"),
        exercise(17, "Latzug breit", "RUECKEN", "BIZEPS", "KABEL"),
        exercise(18, "Latzug eng", "RUECKEN", "BIZEPS", "KABEL"),
        exercise(19, "Kabelrudern sitzend", "RUECKEN", "BIZEPS", "KABEL"),
        exercise(20, "T-Bar Rudern", "RUECKEN", "BIZEPS", "LANGHANTEL"),
        exercise(21, "Rudermaschine", "RUECKEN", "BIZEPS", "MASCHINE"),
        exercise(22, "Kreuzheben", "RUECKEN", "BEINE,GESAESS,CORE", "LANGHANTEL"),
        exercise(23, "Hyperextension", "RUECKEN", "GESAESS", "EIGENGEWICHT"),
        exercise(24, "Face Pulls", "RUECKEN", "SCHULTERN", "KABEL"),
        exercise(25, "Einarmiges Kabelziehen", "RUECKEN", "BIZEPS", "KABEL"),
        exercise(26, "Kniebeuge (Langhantel)", "BEINE", "GESAESS,CORE", "LANGHANTEL"),
        exercise(27, "Frontkniebeuge", "BEINE", "CORE,GESAESS", "LANGHANTEL"),
        exercise(28, "Rumänisches Kreuzheben", "BEINE", "GESAESS,RUECKEN", "LANGHANTEL"),
        exercise(29, "Rumänisches Kreuzheben (Kurzhantel)", "BEINE", "GESAESS,RUECKEN", "KURZHANTEL"),
        exercise(30, "Beinpresse", "BEINE", "GESAESS", "MASCHINE"),
        exercise(31, "Hackenschmidt", "BEINE", "GESAESS", "MASCHINE"),
        exercise(32, "Ausfallschritte (Langhantel)", "BEINE", "GESAESS", "LANGHANTEL"),
        exercise(33, "Ausfallschritte (Kurzhantel)", "BEINE", "GESAESS", "KURZHANTEL"),
        exercise(34, "Bulgarische Kniebeuge", "BEINE", "GESAESS", "KURZHANTEL"),
        exercise(35, "Beinstrecker", "BEINE", "", "MASCHINE"),
        exercise(36, "Beinbeuger liegend", "BEINE", "", "MASCHINE"),
        exercise(37, "Beinbeuger sitzend", "BEINE", "", "MASCHINE"),
        exercise(38, "Goblet Squat", "BEINE", "GESAESS,CORE", "KURZHANTEL"),
        exercise(39, "Sumo Kreuzheben", "BEINE", "GESAESS,RUECKEN", "LANGHANTEL"),
        exercise(40, "Hip Thrust (Langhantel)", "GESAESS", "BEINE", "LANGHANTEL"),
        exercise(41, "Hip Thrust (Maschine)", "GESAESS", "BEINE", "MASCHINE"),
        exercise(42, "Glute Kickback (Kabel)", "GESAESS", "", "KABEL"),
        exercise(43, "Abduktion (Maschine)", "GESAESS", "", "MASCHINE"),
        exercise(44, "Schulterdrücken (Langhantel)", "SCHULTERN", "TRIZEPS", "LANGHANTEL"),
        exercise(45, "Schulterdrücken (Kurzhantel)", "SCHULTERN", "TRIZEPS", "KURZHANTEL"),
        exercise(46, "Schulterdrücken (Maschine)", "SCHULTERN", "TRIZEPS", "MASCHINE"),
        exercise(47, "Seitheben (Kurzhantel)", "SCHULTERN", "", "KURZHANTEL"),
        exercise(48, "Seitheben (Kabel)", "SCHULTERN", "", "KABEL"),
        exercise(49, "Frontheben", "SCHULTERN", "BRUST", "KURZHANTEL"),
        exercise(50, "Aufrechtes Rudern", "SCHULTERN", "BIZEPS", "LANGHANTEL"),
        exercise(51, "Arnold Press", "SCHULTERN", "TRIZEPS", "KURZHANTEL"),
        exercise(52, "Reverse Fly (Kurzhantel)", "SCHULTERN", "RUECKEN", "KURZHANTEL"),
        exercise(53, "Reverse Fly (Maschine)", "SCHULTERN", "RUECKEN", "MASCHINE"),
        exercise(54, "Langhantelcurls", "BIZEPS", "UNTERARME", "LANGHANTEL"),
        exercise(55, "SZ-Curls", "BIZEPS", "UNTERARME", "LANGHANTEL"),
        exercise(56, "Kurzhantelcurls", "BIZEPS", "UNTERARME", "KURZHANTEL"),
        exercise(57, "Hammercurls", "BIZEPS", "UNTERARME", "KURZHANTEL"),
        exercise(58, "Konzentrationscurls", "BIZEPS", "", "KURZHANTEL"),
        exercise(59, "Kabelcurls", "BIZEPS", "UNTERARME", "KABEL"),
        exercise(60, "Schrägbankcurls", "BIZEPS", "", "KURZHANTEL"),
        exercise(61, "Trizepsdrücken am Kabel", "TRIZEPS", "", "KABEL"),
        exercise(62, "Trizepsdrücken Seil", "TRIZEPS", "", "KABEL"),
        exercise(63, "French Press (SZ-Stange)", "TRIZEPS", "", "LANGHANTEL"),
        exercise(64, "Stirndrücken (Kurzhantel)", "TRIZEPS", "", "KURZHANTEL"),
        exercise(65, "Dips (Trizeps)", "TRIZEPS", "BRUST,SCHULTERN", "EIGENGEWICHT"),
        exercise(66, "Kickbacks (Kurzhantel)", "TRIZEPS", "", "KURZHANTEL"),
        exercise(67, "Enges Bankdrücken", "TRIZEPS", "BRUST,SCHULTERN", "LANGHANTEL"),
        exercise(68, "Plank", "CORE", "", "EIGENGEWICHT"),
        exercise(69, "Cable Crunch", "CORE", "", "KABEL"),
        exercise(70, "Beinheben hängend", "CORE", "", "EIGENGEWICHT"),
        exercise(71, "Beinheben liegend", "CORE", "", "EIGENGEWICHT"),
        exercise(72, "Russian Twist", "CORE", "", "EIGENGEWICHT"),
        exercise(73, "Ab-Roller", "CORE", "", "EIGENGEWICHT"),
        exercise(74, "Seitliches Plank", "CORE", "", "EIGENGEWICHT"),
        exercise(75, "Unterarmcurls", "UNTERARME", "", "LANGHANTEL"),
        exercise(76, "Reverse Curls", "UNTERARME", "BIZEPS", "LANGHANTEL"),
        exercise(77, "Wadenheben stehend (Maschine)", "WADEN", "", "MASCHINE"),
        exercise(78, "Wadenheben sitzend", "WADEN", "", "MASCHINE"),
        exercise(79, "Wadenheben an der Beinpresse", "WADEN", "", "MASCHINE"),
    )

    private fun exercise(id: Long, name: String, primary: String, secondary: String, category: String) =
        BackupExercise(id, name, primary, secondary, category, isCustom = false)
}
